backend:
  name: github
  repo: ashalfarhan/prod-docs
  branch: main
  base_url: https://prod-docs-oauth.ashalfarhan8.workers.dev

media_folder: 'docs/public/media'

public_folder: '/media'

slug:
  encoding: ascii
  clean_accent: true
  sanitize_replacement: '-'

collections:
  - label: 'Documentation Page'
    name: 'pages'
    folder: 'docs'
    create: true
    delete: false
    slug: '{{slug}}'
    identifier_field: 'title'
    summary: '{{title}} - {{slug}}'
    filter:
      - field: layout
        value: doc
    fields:
      - name: 'layout'
        label: 'Layout'
        widget: 'hidden'
        default: 'doc'
        hint: 'Markdown Layout'
      - name: 'title'
        label: 'Title'
        widget: 'string'
        hint: 'Title to improve SEO'
      - name: 'description'
        label: 'Description'
        widget: 'text'
        hint: 'Description to improve SEO'
      - name: 'navbar'
        label: 'Show navbar'
        widget: 'boolean'
        required: false
        default: true
      - name: 'sidebar'
        label: 'Show sidebar'
        widget: 'boolean'
        required: false
        default: true
      - name: 'footer'
        label: 'Show footer'
        widget: 'boolean'
        required: false
        default: true
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
